[versions]
agp = "8.9.1"
kotlin = "2.0.21"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"

retrofitVersion = "2.9.0"
okhttp3Version = "4.12.0"
gsonVersion = "2.10.1"

roomVersion = "2.6.1"

hiltVersion = "2.51.1"
hiltNavigationFragmentVersion = "1.2.0"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

retrofit = {group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofitVersion"}
retrofit-rxjava3-adapter = {group = "com.squareup.retrofit2", name = "adapter-rxjava3", version.ref = "retrofitVersion"}
retrofit-json-converter = {group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofitVersion"}

okhttp = {group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp3Version"}
okhttp-intercepter = {group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp3Version"}
gson = {group = "com.google.code.gson", name = "gson", version.ref = "gsonVersion"}

room-ktx = {group = "androidx.room", name = "room-ktx", version.ref = "roomVersion"}
room-runtime = {group = "androidx.room", name = "room-runtime", version.ref = "roomVersion"}
room-compiler = {group = "androidx.room", name = "room-compiler", version.ref = "roomVersion"}
room-common = {group = "androidx.room", name = "room-common", version.ref = "roomVersion"}

hilt-android = {group = "com.google.dagger", name = "hilt-android", version.ref = "hiltVersion"}
hilt-compiler = {group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hiltVersion"}
hilt-navigation = {group = "androidx.hilt", name = "hilt-navigation-fragment", version.ref = "hiltNavigationFragmentVersion"}

[bundles]
network-dependencies = [
    "retrofit",
    "retrofit.rxjava3.adapter",
    "retrofit.json.converter",
    "okhttp",
    "okhttp.intercepter",
    "gson",
]

room-dependencies = [
    "room-ktx",
    "room-runtime",
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltVersion" }

